apiVersion: v1
clusters:
  - cluster:
      insecure-skip-tls-verify: true
      server: https://localhost:6443
    name: docker-desktop
contexts:
  - context:
      cluster: docker-desktop
      user: docker-desktop
    name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
  - name: docker-desktop
    user:
      token: 1

